### Defaults ###

# Larger history
set -g history-limit 100000

# Enable vim layout
setw -g mode-keys vi

# Obvious
set -g mouse on

### Keymaps ###

# Use logical '|' and '-' for vertical and horizontal splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Remap stupid C-b keymap 
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


# Vim-lime movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-like resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Keymap to zoom into pane
bind z resize-pane -Z

### Other ####

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
